/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const PlantDiseaseResult = IDL.Record({
  'suggestedTreatment' : IDL.Text,
  'leafImage' : ExternalBlob,
  'diseaseName' : IDL.Text,
  'timestamp' : Time,
  'confidencePercentage' : IDL.Float64,
});
export const CropYieldResult = IDL.Record({
  'timestamp' : Time,
  'accuracyScore' : IDL.Float64,
  'predictedYield' : IDL.Float64,
});
export const IrrigationResult = IDL.Record({
  'waterRequired' : IDL.Float64,
  'timestamp' : Time,
  'recommendation' : IDL.Bool,
});
export const IrrigationInput = IDL.Record({
  'temperature' : IDL.Float64,
  'weatherCondition' : IDL.Text,
  'soilMoistureLevel' : IDL.Float64,
});
export const CropYieldInput = IDL.Record({
  'fertilizerUsage' : IDL.Float64,
  'soilType' : IDL.Text,
  'temperature' : IDL.Float64,
  'humidity' : IDL.Float64,
  'rainfall' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearHistory' : IDL.Func([], [], []),
  'detectDisease' : IDL.Func([ExternalBlob], [PlantDiseaseResult], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCropYieldHistory' : IDL.Func([], [IDL.Vec(CropYieldResult)], ['query']),
  'getIrrigationHistory' : IDL.Func([], [IDL.Vec(IrrigationResult)], ['query']),
  'getIrrigationRecommendation' : IDL.Func(
      [IrrigationInput],
      [IrrigationResult],
      [],
    ),
  'getPlantDiseaseHistory' : IDL.Func(
      [],
      [IDL.Vec(PlantDiseaseResult)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'predictYield' : IDL.Func([CropYieldInput], [CropYieldResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const PlantDiseaseResult = IDL.Record({
    'suggestedTreatment' : IDL.Text,
    'leafImage' : ExternalBlob,
    'diseaseName' : IDL.Text,
    'timestamp' : Time,
    'confidencePercentage' : IDL.Float64,
  });
  const CropYieldResult = IDL.Record({
    'timestamp' : Time,
    'accuracyScore' : IDL.Float64,
    'predictedYield' : IDL.Float64,
  });
  const IrrigationResult = IDL.Record({
    'waterRequired' : IDL.Float64,
    'timestamp' : Time,
    'recommendation' : IDL.Bool,
  });
  const IrrigationInput = IDL.Record({
    'temperature' : IDL.Float64,
    'weatherCondition' : IDL.Text,
    'soilMoistureLevel' : IDL.Float64,
  });
  const CropYieldInput = IDL.Record({
    'fertilizerUsage' : IDL.Float64,
    'soilType' : IDL.Text,
    'temperature' : IDL.Float64,
    'humidity' : IDL.Float64,
    'rainfall' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearHistory' : IDL.Func([], [], []),
    'detectDisease' : IDL.Func([ExternalBlob], [PlantDiseaseResult], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCropYieldHistory' : IDL.Func([], [IDL.Vec(CropYieldResult)], ['query']),
    'getIrrigationHistory' : IDL.Func(
        [],
        [IDL.Vec(IrrigationResult)],
        ['query'],
      ),
    'getIrrigationRecommendation' : IDL.Func(
        [IrrigationInput],
        [IrrigationResult],
        [],
      ),
    'getPlantDiseaseHistory' : IDL.Func(
        [],
        [IDL.Vec(PlantDiseaseResult)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'predictYield' : IDL.Func([CropYieldInput], [CropYieldResult], []),
  });
};

export const init = ({ IDL }) => { return []; };